#!/bin/sh

# users=$(eval getent passwd {$(awk '/^UID_MIN/ {print $2}' /etc/login.defs)..$(awk '/^UID_MAX/ {print $2}' /etc/login.defs)} | cut -d: -f1)
users=$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd)
for i in ${users[@]}; do
# 	mkdir -p /home/$i/.gkrellm2/
# 	chown $i:$i /home/$i/.gkrellm2/
	rsync -Cazog --chown=$i:$i /etc/skel/.gkrellm2/theme_config /home/$i/.gkrellm2/theme_config
done

